### ISSUE TITLE
[Bug]-Windows 上用不了

### ISSUE THREAD

**Issue by AngusYGChen** [observerw/obsidian-code-link#1]
文件资源管理器
![image](https://github.com/user-attachments/assets/32081a32-56d1-46f4-9c63-3852c528bd67)
Obsidian
![image](https://github.com/user-attachments/assets/55de3d82-a7fa-4f76-b628-3aef841bfd75)
![image](https://github.com/user-attachments/assets/ac15b640-7ff5-4d6a-ae68-edae526d7357)

**Comment by observerw** [comment]
似乎将导入方式从符号链接改为硬链接能够解决此问题。 
[1.0.4](https://github.com/observerw/obsidian-code-link/releases/tag/1.0.4)修复了该问题，请再次尝试，如果仍有问题请随时重新打开此issue。
